### ISSUE TITLE
Any chance that amd gpus get some love too?

### ISSUE THREAD

**Issue by e9r8we90r8** [OhGodACompany/OhGodAnETHlargementPill#68] opened 2018-06-05 15:19 UTC

**Comment by michstuff** [comment] 2018-06-14 11:57
guess not...

**Comment by jimmykl** [comment] 2018-06-14 23:03
I think OhGodACompany's AMD VBIOS tuning means there's no need for embiggening those cards

**Comment by jimmykl** [comment] 2018-06-14 23:06
Also this is a duplicate of #66 😉 If you could close it that'll help keep things in order

**Closed** 2018-06-15 06:51 UTC
