### ISSUE TITLE
GTX 1080 Hashrate fluctuating/low

### ISSUE THREAD

**Issue by derrmono** [OhGodACompany/OhGodAnETHlargementPill#45] opened 2018-05-01 22:27 UTC
My 1080's hashrate likes to fluctuate from ~27 MH/s to as low as ~17 MH/s. I'm not sure if I did the --revA correctly (I used powershell) Any help?

Edit: FIXED!

**Comment by FatShady2017** [comment] 2018-05-02 11:12
What is the reference hash for gtx1080's using this app?

**Comment by jimmykl** [comment] 2018-05-02 12:39
Anywhere from 30-38 has been reported  https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Hashrate-Results

**Comment by OhGodABird** [comment] 2018-06-21 10:28
Seems like the issue is fixed, but not closed, therefore I'm closing it.

**Closed by OhGodABird** 2018-06-21 10:28 UTC
